# Welcome to Jekyll Settings!
title: The build!
email: s.chepov@abv.bg
description: It works fine!
baseurl: "/website-to-glory" # the subpath of your site, e.g. /blog
url: "https://stoyanchepov.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: schepov
github_username:  StoyanChepov
destination: docs
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - docs
  - node_modules
  - scss
